- name: Create instances ("{{ instances }}")
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    gcp_instance_name: "{{ instances }}"

  pre_tasks:
    - name: Add external configs
      ansible.builtin.include_vars:
        dir: "./config"
        depth: 1
        ignore_files: "credentials.yaml"
        extensions:
          - 'yaml'

  tasks:
    - name: create a network
      google.cloud.gcp_compute_network:
        name: network-instance
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        auto_create_subnetworks: "{{ gcp_auto_create_subnet }}"
        state: present
      register: network

    - name: create a disk
      google.cloud.gcp_compute_disk:
        name: "{{ gcp_instance_name }}"
        size_gb: 50
        source_image: "{{ gcp_machine_source_image }}"
        zone: "{{ gcp_default_zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: disk

    - name: create a address
      google.cloud.gcp_compute_address:
        name: "{{ gcp_instance_name }}"
        region: "{{ gcp_default_region }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: address

    - name: create a instance
      google.cloud.gcp_compute_instance:
        name: "{{ gcp_instance_name }}"
        machine_type: "{{ gcp_machine_type }}"
        disks:
          - auto_delete: 'true'
            boot: 'true'
            interface: SCSI
            source: "{{ disk }}"
            type: PERSISTENT
        metadata:
          serial-port-enable: "true"
        labels:
          environment: production
        service_accounts:
          - email: "master-it-sa@it-sa-project.iam.gserviceaccount.com"
            scopes: "https://www.googleapis.com/auth/cloud-platform"
        network_interfaces:
          - network: "{{ network }}"
            access_configs:
              - name: External NAT
                nat_ip: "{{ address }}"
                type: ONE_TO_ONE_NAT
        zone: "{{ gcp_default_zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
